title: Jiayin Zhu's Homepage
page-top-title: Jiayin Zhu
top-section-bg-text: Just do it
home-subtitle: Jiayin Zhu&ensp;|&ensp;朱佳印
email: "zjy2000@stu.xjtu.edu.cn"
copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
